version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ChiwiTech$2024
      POSTGRES_DB: SGIER
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://admin:ChiwiTech$2024@postgres:5432/SGIER
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  pgdata:
  n8n_data:
